### ISSUE TITLE
Add support for other registries

### ISSUE THREAD

**Issue by cusspvz** [bravissimolabs/docker-generate-npm-authtoken#1]
By default, authentication spots `registry.npmjs.org`. If you have a private registry such as **sinopia** and you try to generate an `npm login` without it, it will fetch auth token from the npm default one and obviously it won't work on your private one.

Just add `--registry="$NPM_REGISTRY"` on your `npm.sh`.

I wouldn't mind to PR those changes, but unfortunately I'm busy as hell, and inspite I've liked the concept you introduced here, I won't use it by now.

Thanks,
José Moreira

**Comment by adamkdean** [comment]
Hi José,

Good point, we should support the ability to specific alternate registries.

I'll take a look into it.

Adam

**Comment by adamkdean** [comment]
@cusspvz I've implemented this small change now, and tested it locally with https://skimdb.npmjs.com/registry, once Docker Hub has built the image, could you test it with your private registries and let me know if it all works OK?

Thanks, appreciate the feedback as well!

**Comment by adamkdean** [comment]
Going to close this now.
